name: d3f_modular
version: 1.0.0+1
publish_to: none
description: d3f_modular
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  d3f_dependency_manager: 
    git: 
      url: https://github.com/DanhDue-ExOICTIF/d3f_dependency_manager.git
      ref: develop

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.10+1
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  hive_generator: ^1.1.3
  freezed: ^2.1.0+1
  flutter_gen_runner: ^5.0.1
  get_cli: ^0.2.30
  test: ^1.21.4
  flutter_test: 
    sdk: flutter

flutter_gen: 
  output: lib/generated/
  integrations: 
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true
  assets: 
    outputs: 
      class_name: MyAssets
      style: dot-delimiter
      package_parameter_enabled: false
    enabled: true
  line_length: 80

flutter: 
  assets: 
    - assets/images/
    - assets/lotties/
    - assets/jsons/
  uses-material-design: true

